### ISSUE TITLE
Do not execute lock fail_complex_cond_put

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud-docker/litmus#1]
As documented by @evert the lock test 20. fail_complex_cond_put. is wrongly implemented in litmus.
see  https://github.com/sabre-io/dav/pull/702#issuecomment-129531905
and http://lists.manyfish.co.uk/pipermail/litmus/2015-February/000350.html

We need a way to not execute this test

**Comment by DeepDiver1975** [comment]
Solution A:
- fork https://github.com/tolsen/litmus and patch it

Solution B:
- apply patch within the docker image

@patrickjahns @tboerger what is the prefered way?

**Comment by tboerger** [comment]
In the past I used the patch way for that, like https://github.com/owncloud-docker/litmus/commit/15a086641b8b7d7f5a722e9ee764a690e9be89aa#diff-3254677a7917c6c01f55212f86c57fbf.

But instead of adding the patch to the docker image I would create a gist and fetch that.

**Comment by DeepDiver1975** [comment]
Let me see if I find the time to work on this by patching it from gist. THX

**Comment by DeepDiver1975** [comment]
location/owner of the gist? personal seems errorious ...

**Comment by tboerger** [comment]
@DeepDiver1975 than create one as @ownclouders?

**Comment by DeepDiver1975** [comment]
oh lord - the site is down again
we need an alternative hosting source for this tar ball

**Comment by tboerger** [comment]
Within the Dockerfile I'm already using https://github.com/owncloud/core/files/1426448/litmus-0.13.tar.gz but we could also provide this archive via minio?

**Comment by DeepDiver1975** [comment]
> but we could also provide this archive via minio?

Let's just keep this in github -- maybe not the most obvious place .... but it works and is available for everybody

**Comment by evert** [comment]
fwiw, sabre/dav is also wrong in this regard...

**Comment by DeepDiver1975** [comment]
> fwiw, sabre/dav is also wrong in this regard...

so we better fix sabre/dav? :confused:

**Comment by evert** [comment]
Yea I think that would be ideal =)

**Comment by DeepDiver1975** [comment]
> Yea I think that would be ideal =)

challenge accepted

**Comment by evert** [comment]
awesome =)

Here's the real ticket for it:

https://github.com/sabre-io/dav/issues/715
